### ISSUE TITLE
The the resend mail confirmation link alert is not clickable

### ISSUE THREAD

**Issue by borisrorsvort** [WelcometoMyGarden/welcometomygarden#31]
<img width="1040" alt="CleanShot 2020-06-25 at 12 12 20@2x" src="https://user-images.githubusercontent.com/39081/85701110-5814b080-b6dd-11ea-9731-3e00ca045ecc.png">

Basically you cannot click on resend. Tested in latest safari and chrome

**Comment by MichielLeyman** [comment]
Thanks for reporting this. I can see that you're not logged in - clicking to resend the email didn't work because we check for the signed in user's email.

I removed the click feature from the notification, and I'm instead redirecting to the account page as per https://github.com/WelcometoMyGarden/welcometomygarden/commit/1066abda597b2765dc9c92ad6f0a04c6c5d61a20.
A resend button is available there.

Please create a new issues should you still have a problem :)
